#!/bin/bash

set -eu


## works both under bash and sh
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
SCRIPT_PATH=$(readlink -f "$0")


DUMP_DIR="$SCRIPT_DIR/dump_scripts"
OUTPUT_PATH="$SCRIPT_DIR/rosdiagram/dumpscripts.py"


SCRIPT_NAME=$(basename $SCRIPT_PATH)

cat > $OUTPUT_PATH << EOF
#
# This file is automatically generated using '$SCRIPT_NAME' script. Any changes will be lost.
#
#
# Copyright (c) 2022, Arkadiusz Netczuk <dev.arnet@gmail.com>
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause license found in the
# LICENSE file in the root directory of this source tree.
#


EOF


SCRIPTS_LIST=""

for FILE in $DUMP_DIR/*; do
    BASENAME=$(basename $FILE)
    VAR_NAME=${BASENAME^^}
    VAR_NAME=${VAR_NAME/./_}

    echo "appending $FILE"
    echo "## $BASENAME" >> $OUTPUT_PATH
    echo "$VAR_NAME = ( \"$BASENAME\"," >> $OUTPUT_PATH
    
    ## insert content of file 
    echo '"""\' >> $OUTPUT_PATH
    base64 $FILE >> $OUTPUT_PATH
    #cat $FILE >> $OUTPUT_PATH
    echo '"""' >> $OUTPUT_PATH
    
    echo ')' >> $OUTPUT_PATH 
    echo -e "\n" >> $OUTPUT_PATH

    SCRIPTS_LIST="$VAR_NAME, ${SCRIPTS_LIST}" 
done


echo "# all scripts"  >> $OUTPUT_PATH
echo "SCRIPTS_LIST = [ $SCRIPTS_LIST ]"  >> $OUTPUT_PATH


echo "done"
